// (c) mddbook, wasowski, tberger

lazy val root = (project in file(".")).settings (

  organization := "mdsebook",
  name := "Scala, EMF, #noEclipse",
  version := "0.02",
  // stick to Scala version supported by Scala IDE 
  // (then we can switch between Eclipse/Intellij/SBT)
  scalaVersion := "2.10.6",

  scalacOptions += "-deprecation",
  scalacOptions += "-feature",
  scalacOptions += "-language:implicitConversions",

  // include to the code generated by Eclipse in a separate EMF project
  unmanagedSourceDirectories in Compile += baseDirectory.value / "../mdsebook.fsm/src/",
  unmanagedSourceDirectories in Test += baseDirectory.value / "../mdsebook.fsm/src/",

  libraryDependencies += "org.eclipse.emf" % "org.eclipse.emf.ecore" % "2.11.+",
  libraryDependencies += "org.eclipse.emf" % "org.eclipse.emf.ecore.xmi" % "2.11.+",
  libraryDependencies += "org.eclipse.emf" % "org.eclipse.emf.common" % "2.11.+",
  libraryDependencies += "org.scalatest" %% "scalatest" % "2.2.6" % "test"
)
