<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="model" nsURI="http://www.example.org/dk.itu.chomsky.configurator.model"
    nsPrefix="dk.itu.chomsky.configurator.model">
  <eClassifiers xsi:type="ecore:EClass" name="Model" eSuperTypes="#//ModelElem">
    <eStructuralFeatures xsi:type="ecore:EReference" name="children" upperBound="-1"
        eType="#//ModelChild" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="types" upperBound="-1"
        eType="#//EnumType" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ModelChild" abstract="true" eSuperTypes="#//LabeledElem"/>
  <eClassifiers xsi:type="ecore:EClass" name="ProductGroup" eSuperTypes="#//ModelChild">
    <eStructuralFeatures xsi:type="ecore:EReference" name="children" upperBound="-1"
        eType="#//ModelChild" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Product" eSuperTypes="#//ModelChild #//ModelElem">
    <eStructuralFeatures xsi:type="ecore:EReference" name="children" upperBound="-1"
        eType="#//ProductChild" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="constraints" upperBound="-1"
        eType="#//Constraint" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ProductChild" abstract="true" eSuperTypes="#//LabeledElem"/>
  <eClassifiers xsi:type="ecore:EClass" name="ParamGroup" eSuperTypes="#//ProductChild">
    <eStructuralFeatures xsi:type="ecore:EReference" name="children" upperBound="-1"
        eType="#//ProductChild" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Param" abstract="true" eSuperTypes="#//ProductChild #//ModelElem">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="optional" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="EnumType" eSuperTypes="#//ModelElem">
    <eStructuralFeatures xsi:type="ecore:EReference" name="values" upperBound="-1"
        eType="#//EnumVal" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="EnumVal" eSuperTypes="#//ModelElem"/>
  <eClassifiers xsi:type="ecore:EClass" name="NamedElem" abstract="true">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="LabeledElem" abstract="true">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="label" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ModelElem" abstract="true" eSuperTypes="#//LabeledElem #//NamedElem"/>
  <eClassifiers xsi:type="ecore:EEnum" name="PrimitiveType">
    <eLiterals name="IntTy"/>
    <eLiterals name="BoolTy" value="1"/>
    <eLiterals name="DoubleTy" value="2"/>
    <eLiterals name="TextTy" value="3"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="PrimParam" eSuperTypes="#//Param">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="type" eType="#//PrimitiveType"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="EnumParam" eSuperTypes="#//Param">
    <eStructuralFeatures xsi:type="ecore:EReference" name="type" lowerBound="1" eType="#//EnumType"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Constraint" eSuperTypes="#//LabeledElem">
    <eStructuralFeatures xsi:type="ecore:EReference" name="expr" lowerBound="1" eType="#//Expr"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="param" eType="#//Param"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Expr" abstract="true"/>
  <eClassifiers xsi:type="ecore:EClass" name="ConstNum" eSuperTypes="#//Expr">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="value" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDouble"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Plus" eSuperTypes="#//BinOp"/>
  <eClassifiers xsi:type="ecore:EClass" name="Minus" eSuperTypes="#//BinOp"/>
  <eClassifiers xsi:type="ecore:EClass" name="Leq" eSuperTypes="#//BinOp"/>
  <eClassifiers xsi:type="ecore:EClass" name="Geq" eSuperTypes="#//BinOp"/>
  <eClassifiers xsi:type="ecore:EClass" name="Eq" eSuperTypes="#//BinOp"/>
  <eClassifiers xsi:type="ecore:EClass" name="Lt" eSuperTypes="#//BinOp"/>
  <eClassifiers xsi:type="ecore:EClass" name="Gt" eSuperTypes="#//BinOp"/>
  <eClassifiers xsi:type="ecore:EClass" name="ConstBool" eSuperTypes="#//Expr">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="value" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Mult" eSuperTypes="#//BinOp"/>
  <eClassifiers xsi:type="ecore:EClass" name="BinOp" abstract="true" eSuperTypes="#//Expr">
    <eStructuralFeatures xsi:type="ecore:EReference" name="left" lowerBound="1" eType="#//Expr"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="right" lowerBound="1" eType="#//Expr"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Div" eSuperTypes="#//BinOp"/>
  <eClassifiers xsi:type="ecore:EClass" name="And" eSuperTypes="#//BinOp"/>
  <eClassifiers xsi:type="ecore:EClass" name="Or" eSuperTypes="#//BinOp"/>
  <eClassifiers xsi:type="ecore:EClass" name="ParamValueRef" eSuperTypes="#//Expr">
    <eStructuralFeatures xsi:type="ecore:EReference" name="param" eType="#//Param"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ValueRef" eSuperTypes="#//Expr">
    <eStructuralFeatures xsi:type="ecore:EReference" name="enumVal" lowerBound="1"
        eType="#//EnumVal"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ConstString" eSuperTypes="#//Expr">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="value" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Not" eSuperTypes="#//Expr">
    <eStructuralFeatures xsi:type="ecore:EReference" name="expr" lowerBound="1" eType="#//Expr"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ITE" eSuperTypes="#//Expr">
    <eStructuralFeatures xsi:type="ecore:EReference" name="guard" lowerBound="1" eType="#//Expr"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="trueBranch" lowerBound="1"
        eType="#//Expr" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="falseBranch" lowerBound="1"
        eType="#//Expr" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="FunApp" eSuperTypes="#//Expr">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="args" upperBound="-1" eType="#//Expr"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Neg" eSuperTypes="#//Expr">
    <eStructuralFeatures xsi:type="ecore:EReference" name="expr" lowerBound="1" eType="#//Expr"
        containment="true"/>
  </eClassifiers>
</ecore:EPackage>
