/*
 * generated by Xtext 2.10.0
 */
package dk.itu.chomsky.configurator;


/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
public class ConfigDSLRuntimeModule extends AbstractConfigDSLRuntimeModule {
}
