/*
 * generated by Xtext 2.10.0
 */
package dk.itu.chomsky.configurator


/**
 * Initialization support for running Xtext languages without Equinox extension registry.
 */
class ConfigDSLStandaloneSetup extends ConfigDSLStandaloneSetupGenerated {

	def static void doSetup() {
		new ConfigDSLStandaloneSetup().createInjectorAndDoEMFRegistration()
	}
}
