/*
 * generated by Xtext 2.10.0
 */
package dk.itu.chomsky.configurator;

import org.eclipse.emf.ecore.EPackage;

import com.google.inject.Injector;

import dk.itu.chomsky.configurator.model.ModelPackage;

/**
 * Initialization support for running Xtext languages without Equinox extension registry.
 */
public class ConfigDSLStandaloneSetup extends ConfigDSLStandaloneSetupGenerated {

	public static void doSetup() {
		new ConfigDSLStandaloneSetup().createInjectorAndDoEMFRegistration();
	}				
	
	// important to add this method - otherwise the JUnit tests will fail with unresolved proxy
	@Override
    public void register(Injector injector) {
		String ns = "http://www.example.org/dk.itu.chomsky.configurator.model";
        if (!EPackage.Registry.INSTANCE.containsKey(ns)) {
            EPackage.Registry.INSTANCE.put(ns, ModelPackage.eINSTANCE);
        }
        super.register(injector);
    }
}
