/*
 * generated by Xtext 2.10.0
 */
package dk.itu.chomsky.configurator.generator;

import org.eclipse.emf.ecore.resource.Resource;

import dk.itu.chomsky.configurator.model.Model;
import dk.itu.chomsky.configurator.model.ModelELem;
import dk.itu.chomsky.configurator.scala.*;
import org.eclipse.xtext.generator.AbstractGenerator;
import org.eclipse.xtext.generator.IFileSystemAccess2;
import org.eclipse.xtext.generator.IGeneratorContext;

/**
 * Generates code from your model files on save.
 * 
 * See https://www.eclipse.org/Xtext/documentation/303_runtime_concepts.html#code-generation
 */
public class ConfigDSLGenerator extends AbstractGenerator {
	
	@Override
	public void doGenerate(Resource input, IFileSystemAccess2 fsa, IGeneratorContext context) {
//		input.getAllContents().forEachRemaining(obj -> {
//			if (obj instanceof ModelELem) {
//				ModelELem elem = (ModelELem)obj;
//				fsa.generateFile(elem.getName() + ".json", Chomsky.generateJson(elem));
//			}
//		});

		String contents = Chomsky.generateJson((Model)input.getAllContents().next());
		fsa.generateFile("output.json", contents);
		// TODO Auto-generated method stub
		System.out.println("doGenerate");
	}
}
