/*
 * generated by Xtext 2.10.0
 */
package dk.itu.chomsky.configurator.ui;

import org.eclipse.ui.plugin.AbstractUIPlugin;

/**
 * Use this class to register components to be used within the Eclipse IDE.
 */
public class ConfigDSLUiModule extends AbstractConfigDSLUiModule {

	public ConfigDSLUiModule(AbstractUIPlugin plugin) {
		super(plugin);
	}
}
