<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="ConfiguratorModel" nsURI="http://dk.itu.dsl.configurator" nsPrefix="dk.itu.dsl.configurator">
  <eClassifiers xsi:type="ecore:EClass" name="ConfiguratorModel" eSuperTypes="#//NamedType">
    <eStructuralFeatures xsi:type="ecore:EReference" name="products" upperBound="-1"
        eType="#//Product" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="producttypes" lowerBound="1"
        upperBound="-1" eType="#//ProductType" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="datatypes" upperBound="-1"
        eType="#//DataType" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Product" eSuperTypes="#//NamedType">
    <eStructuralFeatures xsi:type="ecore:EReference" name="parameters" upperBound="-1"
        eType="#//Parameter" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="producttype" lowerBound="1"
        eType="#//ProductType"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="NamedType" abstract="true">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ProductType" eSuperTypes="#//NamedType"/>
  <eClassifiers xsi:type="ecore:EClass" name="Parameter" abstract="true">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="optional" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="count" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"
        defaultValueLiteral="1"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="conformsTo" lowerBound="1"
        eType="#//DataType"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="value" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="constraint" eType="#//Constraint"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="PredefinedConfig" eSuperTypes="#//Parameter"/>
  <eClassifiers xsi:type="ecore:EClass" name="RuntimeConfig" eSuperTypes="#//Parameter"/>
  <eClassifiers xsi:type="ecore:EClass" name="Constraint" abstract="true"/>
  <eClassifiers xsi:type="ecore:EClass" name="DataType" abstract="true" eSuperTypes="#//NamedType"/>
  <eClassifiers xsi:type="ecore:EClass" name="ValueList" eSuperTypes="#//DataType">
    <eStructuralFeatures xsi:type="ecore:EReference" name="elements" upperBound="-1"
        eType="#//Element" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="belongsTo" lowerBound="1"
        eType="#//ProductType"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Element">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="value" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="IntRange" eSuperTypes="#//DataType">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="from" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="to" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Boolean" instanceClassName="EBoolean"
      eSuperTypes="#//Literal"/>
  <eClassifiers xsi:type="ecore:EClass" name="Date" instanceClassName="EDate" eSuperTypes="#//Literal"/>
  <eClassifiers xsi:type="ecore:EClass" name="Integer" instanceClassName="EInt" eSuperTypes="#//Literal"/>
  <eClassifiers xsi:type="ecore:EClass" name="Literal" abstract="true" eSuperTypes="#//DataType"/>
  <eClassifiers xsi:type="ecore:EClass" name="String" instanceClassName="EString"
      eSuperTypes="#//Literal"/>
  <eClassifiers xsi:type="ecore:EClass" name="ValueContainedIn" eSuperTypes="#//Predicate">
    <eStructuralFeatures xsi:type="ecore:EReference" name="valuelist" lowerBound="1"
        eType="#//ValueList"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="IfThenElse" eSuperTypes="#//Constraint">
    <eStructuralFeatures xsi:type="ecore:EReference" name="then" lowerBound="1" eType="#//Literal"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="predicate" lowerBound="1"
        eType="#//Predicate" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="else" eType="#//Literal"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Predicate" abstract="true"/>
</ecore:EPackage>
